<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 02.08.2017
 * Time: 5:38
 */

namespace app\modules\admin\controllers;

use Yii;
use pheme\settings\components\Settings;
use app\modules\admin\components\BaseController;
use app\modules\admin\models\settings\Main;

class SettingsController extends BaseController
{
    public function beforeAction($action)
    {
        \Yii::$app->getModule('settings')->init(); // make sure this module is init first
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionMain()
    {
        $model = new Main();
        $setting = Yii::$app->settings; /** @var Settings $settings */
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            foreach ($model->toArray() as $key => $value) {
                $setting->set($key, $value, $model->formName(), gettype($value));
            }
        }
        foreach ($model->attributes() as $key) {
            $model->{$key} = $setting->get($key, $model->formName());
        }
        return $this->render('main', ['model' => $model]);
    }
}