<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 30.07.2017
 * Time: 2:59
 */

namespace app\modules\api\models;


use yii\helpers\ArrayHelper;

class File extends \app\models\File
{
    public function fields()
    {
        return ArrayHelper::merge(parent::fields(), [
            'url',
        ]);
    }

    public function formName()
    {
        return ''; // TODO: Change the autogenerated stub
    }
}