<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 27.07.2017
 * Time: 22:15
 */

namespace app\modules\api\models;


use yii\helpers\ArrayHelper;

/**
 * Class Module
 * @property array $filesAttached
 * @property ModuleFile[] $filesAttachedDb
 * @package app\modules\api\models
 */
class Module extends \app\models\Module
{

    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            ['filesAttached', 'filesValidate', 'params' => [
                'type' => ModuleFile::TYPE_ATTACHED,
                'storeModelsAttribute' => '_filesAttachedStore',
            ], 'skipOnEmpty' => false, 'isEmpty' => function($value) {
                return $value;
            }],
        ]);
    }
    
    public function fields()
    {
        return [
            'id',
            'title',
            'sort',
            'filesAttached',
            'author',
            'fullTitle',
            'test_title',
            'test_comment_after',
            'button_name'
        ];
    }

    public function extraFields()
    {
        return ['themes', 'questions'];
    }

    public function getQuestions()
    {
        return $this->hasMany(Question::className(), ['module_id' => 'id'])->andWhere(['theme_id' => null]);
    }

    public function getThemes()
    {
        return $this->hasMany(Theme::className(), ['module_id' => 'id'])
            ->andWhere(['parent_id' => null])
            ->orderBy(['sort' => Theme::DEFAULT_SORT_ORDER]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFilesAttachedDb()
    {
        return $this->hasMany(ModuleFile::className(), ['module_id' => 'id'])->andWhere(['type' => ModuleFile::TYPE_ATTACHED]);
    }

    /** @var array */
    protected $_filesAttached;
    /** @var ModuleFile[] */
    protected $_filesAttachedStore = [];

    /**
     * @return array
     */
    public function getFilesAttached()
    {
        if ($this->_filesAttached === null) {
            $this->_filesAttached = ArrayHelper::toArray($this->filesAttachedDb);
        }
        return $this->_filesAttached;
    }

    /**
     * @param array $value
     */
    public function setFilesAttached($value)
    {
        $this->_filesAttached = $value;
    }

    /**
     * @param $attribute
     * @param $params
     */
    public function filesValidate($attribute, $params)
    {
        foreach ($this->$attribute as $index => $item) {
            $this->internalFileValidate(
                $attribute,
                $index,
                $item,
                $params['type'],
                $params['storeModelsAttribute']
            );
        }
    }

    protected function internalFileValidate($attribute, $index, $item, $type, $storeModelsAttribute)
    {
        $model = null; /** @var ModuleFile|null $model */
        if (!isset($item['id']) || empty($item['id']) || !($model = ModuleFile::findOne($item['id']))) {
            $model = new ModuleFile();
        }
        $model->load($item, '');
        $model->type = $type;
        if (!$model->validate()) {
            foreach ($model->getFirstErrors() as $attr => $error) {
                $this->addError("$attribute-$model->unique-$attr", $error);
            }
        }
        $this->{$storeModelsAttribute}[] = $model;
        //$this->addError('qqq', 'qqq');
    }

    public function updateFiles()
    {
        foreach (['Attached'] as $attr) {
            $db = "files{$attr}Db";
            $store = "_files{$attr}Store";
            $local = "files{$attr}";
            $delete = ArrayHelper::map($this->$db, 'id', 'id');
            foreach ($this->$store as $model) { /** @var ModuleFile $model */
                $model->module_id = $this->id;
                $model->save(false);
                if (isset($delete[$model->id])) {
                    unset($delete[$model->id]);
                }
            }
            $this->$local = $this->$store;
            ModuleFile::deleteAll(['in', 'id', $delete]);
        }
    }

    public function afterSave($insert, $changedAttributes)
    {
        $this->updateFiles();
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}