<?php

namespace app\modules\api\controllers;

use app\modules\api\models\File;
use yii\rest\ActiveController;

/**
 * Class FileController
 * @package app\modules\api\controllers
 */
class FileController extends ActiveController
{
    public $modelClass = 'app\modules\api\models\File';
    public $createScenario = File::SCENARIO_INSERT;

    //public function actions()
    //{
    //    $actions = parent::actions(); // TODO: Change the autogenerated stub
    //    //unset($actions['create']);
    //    return $actions;
    //}

    //public function actionCreate()
    //{
    //    return [$_POST, $_FILES];
    //}
}